### ISSUE TITLE
Add support for OBS 30.x

### ISSUE THREAD

**Issue by krt222** [norihiro/obs-loudness-dock#9]
It would be great if the plugin supported the latest version of OBS (30.x.). The OBS team uploads .deb files over at https://github.com/obsproject/obs-studio/releases

If this is not feasible or in any case cumbersome, it would be nice to have a standalone version of the plugin that can be run at the command line. This would help avoid launching an old copy of OBS just to check on the levels, while also having the current OBS perform the streaming task.

Thanks!

**Comment by norihiro** [comment]
For the beta version from GitHub, you need to create a symbolic links like this.
```sh
ln -s /usr/lib/x86_64-linux-gnu/obs-plugins/obs-loudness-dock.so /usr/local/lib/obs-plugins/
ln -s /usr/share/obs/obs-plugins/obs-loudness-dock /usr/local/share/obs/obs-plugins/
```

This is because the beta version available on GitHub release page has a different configuration from the packages on PPA. The beta version expects plugins are installed under `/usr/local`, however the PPA release packages expect under `/usr/lib/x86_64-linux-gnu`.
Once the 30.1.0 is released, the issue should be gone.
